-- =============================================================================
-- V2 pipeline initial schema
-- =============================================================================
-- Adds the 13 tables that back the end-to-end data pipeline:
--   hot topic search -> topic plan -> sticker pack -> TK video -> TKShop product
--
-- All `created_at` / `updated_at` / `*_at` are unix epoch INTEGER (seconds).
-- All JSON-shaped fields are TEXT holding json.dumps() output.
-- Foreign keys are declared; runtime enforcement requires PRAGMA foreign_keys=ON
-- (already set by OpsDatabase).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- A.1  Hot topic pool (multi-source: openai_websearch / tavily / perplexity / tiktok_cc)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hot_topics (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  source        TEXT    NOT NULL,
  query         TEXT,
  topic_name    TEXT    NOT NULL,
  raw_payload   TEXT    DEFAULT '{}',
  evidence_urls TEXT    DEFAULT '[]',
  hot_score     REAL    DEFAULT 0,
  region        TEXT    DEFAULT '',
  fetched_at    INTEGER NOT NULL,
  status        TEXT    NOT NULL DEFAULT 'pending'
);
CREATE INDEX IF NOT EXISTS idx_hot_topics_status         ON hot_topics(status);
CREATE INDEX IF NOT EXISTS idx_hot_topics_source_fetched ON hot_topics(source, fetched_at);

-- -----------------------------------------------------------------------------
-- A.2  Topic plan (N series x M previews x K stickers configuration + AI output)
--      Two-step generation: main_raw_text holds the creative model's free-form
--      output; series_payload holds the extractor model's structured JSON.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS topic_plans (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  topic_id        INTEGER NOT NULL REFERENCES hot_topics(id),
  config          TEXT    NOT NULL DEFAULT '{}',
  main_raw_text   TEXT    DEFAULT '',
  series_payload  TEXT    DEFAULT '{}',
  status          TEXT    NOT NULL DEFAULT 'draft',
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_topic_plans_topic  ON topic_plans(topic_id);
CREATE INDEX IF NOT EXISTS idx_topic_plans_status ON topic_plans(status);

-- -----------------------------------------------------------------------------
-- A.2  Single series within a plan (one row = one "套")
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pack_series (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  plan_id          INTEGER NOT NULL REFERENCES topic_plans(id),
  series_idx       INTEGER NOT NULL,
  series_name      TEXT    NOT NULL,
  style_anchor     TEXT    DEFAULT '',
  palette          TEXT    DEFAULT '',
  pack_archetype   TEXT    DEFAULT '',
  priority         TEXT    DEFAULT 'medium',
  metadata_json    TEXT    DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_pack_series_plan ON pack_series(plan_id);

-- -----------------------------------------------------------------------------
-- A.3  Preview images (N per series, generated by gpt-image-2)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pack_previews (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  series_id         INTEGER NOT NULL REFERENCES pack_series(id),
  preview_idx       INTEGER NOT NULL,
  prompt_text       TEXT    DEFAULT '',
  image_path        TEXT    DEFAULT '',
  model_used        TEXT    DEFAULT '',
  generation_status TEXT    NOT NULL DEFAULT 'pending',
  generated_at      INTEGER
);
CREATE INDEX IF NOT EXISTS idx_pack_previews_series ON pack_previews(series_id);
CREATE INDEX IF NOT EXISTS idx_pack_previews_status ON pack_previews(generation_status);

-- -----------------------------------------------------------------------------
-- A.3  Single sticker (image-edit split from a preview)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pack_stickers (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  preview_id   INTEGER NOT NULL REFERENCES pack_previews(id),
  sticker_idx  INTEGER NOT NULL,
  name         TEXT    DEFAULT '',
  description  TEXT    DEFAULT '',
  image_path   TEXT    DEFAULT '',
  is_selected  INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_pack_stickers_preview ON pack_stickers(preview_id);

-- -----------------------------------------------------------------------------
-- A.4  Pack aggregate (one row per series that has been "saved as pack")
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS packs (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  pack_uid           TEXT    NOT NULL UNIQUE,
  series_id          INTEGER NOT NULL REFERENCES pack_series(id),
  display_name       TEXT    DEFAULT '',
  cover_image_path   TEXT    DEFAULT '',
  total_stickers     INTEGER DEFAULT 0,
  status             TEXT    NOT NULL DEFAULT 'active',
  created_at         INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_packs_series ON packs(series_id);
CREATE INDEX IF NOT EXISTS idx_packs_status ON packs(status);

-- -----------------------------------------------------------------------------
-- B.1  TK videos (manual upload + AI caption + scheduled dispatch)
--      Output language: English (overseas market). caption_main_raw_text holds
--      the creative model's free-form output; caption / hashtags hold the
--      extractor model's structured result.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tk_videos (
  id                       INTEGER PRIMARY KEY AUTOINCREMENT,
  pack_id                  INTEGER REFERENCES packs(id),
  account_open_id          TEXT    DEFAULT '',
  local_video_path         TEXT    DEFAULT '',
  video_one_liner          TEXT    DEFAULT '',
  caption_main_raw_text    TEXT    DEFAULT '',
  caption                  TEXT    DEFAULT '',
  hashtags                 TEXT    DEFAULT '[]',
  scheduled_at             INTEGER,
  blotato_post_id          TEXT    DEFAULT '',
  publish_status           TEXT    NOT NULL DEFAULT 'pending',
  published_at             INTEGER,
  publish_error            TEXT    DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_tk_videos_status     ON tk_videos(publish_status);
CREATE INDEX IF NOT EXISTS idx_tk_videos_scheduled  ON tk_videos(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_tk_videos_pack       ON tk_videos(pack_id);

-- -----------------------------------------------------------------------------
-- B.2  TK video metrics (time series, one row per refresh)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tk_video_metrics (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  video_id       INTEGER NOT NULL REFERENCES tk_videos(id),
  view_count     INTEGER DEFAULT 0,
  like_count     INTEGER DEFAULT 0,
  comment_count  INTEGER DEFAULT 0,
  share_count    INTEGER DEFAULT 0,
  fetched_at     INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tk_video_metrics_video_time ON tk_video_metrics(video_id, fetched_at);

-- -----------------------------------------------------------------------------
-- C.1  TKShop products (English buyer-facing copy, two-step generation)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tkshop_products (
  id                       INTEGER PRIMARY KEY AUTOINCREMENT,
  pack_id                  INTEGER REFERENCES packs(id),
  tiktok_product_id        TEXT    DEFAULT '',
  detail_main_raw_text     TEXT    DEFAULT '',
  title                    TEXT    DEFAULT '',
  description_html         TEXT    DEFAULT '',
  selling_points           TEXT    DEFAULT '[]',
  keywords                 TEXT    DEFAULT '[]',
  category_id              TEXT    DEFAULT '928016',
  default_template_json    TEXT    DEFAULT '{}',
  publish_status           TEXT    NOT NULL DEFAULT 'draft',
  created_at               INTEGER NOT NULL,
  published_at             INTEGER
);
CREATE INDEX IF NOT EXISTS idx_tkshop_products_status ON tkshop_products(publish_status);
CREATE INDEX IF NOT EXISTS idx_tkshop_products_pack   ON tkshop_products(pack_id);

-- -----------------------------------------------------------------------------
-- C.2  TKShop product images (manual upload main path + AI generation test path)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tkshop_product_images (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  product_id          INTEGER NOT NULL REFERENCES tkshop_products(id),
  role                TEXT    NOT NULL DEFAULT 'main',
  source              TEXT    NOT NULL DEFAULT 'manual',
  local_path          TEXT    DEFAULT '',
  tiktok_image_uri    TEXT    DEFAULT '',
  sort_order          INTEGER DEFAULT 0,
  ai_prompt           TEXT    DEFAULT '',
  created_at          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tkshop_images_product ON tkshop_product_images(product_id, sort_order);

-- -----------------------------------------------------------------------------
-- C.3  TKShop publish logs (every API call records its full request/response)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tkshop_publish_logs (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  product_id        INTEGER NOT NULL REFERENCES tkshop_products(id),
  attempt_idx       INTEGER NOT NULL DEFAULT 1,
  api_endpoint      TEXT    NOT NULL,
  request_payload   TEXT    DEFAULT '{}',
  response_payload  TEXT    DEFAULT '{}',
  success           INTEGER NOT NULL DEFAULT 0,
  error_code        TEXT    DEFAULT '',
  error_message     TEXT    DEFAULT '',
  created_at        INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tkshop_publish_logs_product_time ON tkshop_publish_logs(product_id, created_at);

-- -----------------------------------------------------------------------------
-- Public  AI call logs (every AI call across the pipeline)
--      For two-step generation, task is suffixed :main / :extract.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_call_logs (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  service             TEXT    NOT NULL,
  model               TEXT    NOT NULL,
  task                TEXT    NOT NULL,
  related_table       TEXT    DEFAULT '',
  related_id          INTEGER,
  prompt_summary      TEXT    DEFAULT '',
  prompt_tokens       INTEGER DEFAULT 0,
  completion_tokens   INTEGER DEFAULT 0,
  latency_ms          INTEGER DEFAULT 0,
  cost_estimate       REAL    DEFAULT 0,
  status              TEXT    NOT NULL DEFAULT 'pending',
  error               TEXT    DEFAULT '',
  created_at          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_call_logs_related ON ai_call_logs(related_table, related_id);
CREATE INDEX IF NOT EXISTS idx_ai_call_logs_task    ON ai_call_logs(task);
CREATE INDEX IF NOT EXISTS idx_ai_call_logs_created ON ai_call_logs(created_at);

-- -----------------------------------------------------------------------------
-- Public  Scheduled jobs (each scheduler tick records an entry)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scheduled_jobs (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  job_name        TEXT    NOT NULL,
  started_at      INTEGER NOT NULL,
  finished_at     INTEGER,
  status          TEXT    NOT NULL DEFAULT 'running',
  affected_rows   INTEGER DEFAULT 0,
  error           TEXT    DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_scheduled_jobs_name_time ON scheduled_jobs(job_name, started_at);
