#!/usr/bin/env python3
"""Seed curated pet-trend sticker preview packs for June 10, 2026."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import scripts.seed_recent_hot_sticker_previews_20260609 as base


base.SOURCE = "manual_curated_pet_hot_20260610"

base.TOPICS = [
    {
        "topic_name": "Cat Distribution System Rescue Notes",
        "query": "Cat Distribution System adoption meme 2026 pet trend",
        "hot_score": 92,
        "region": "GLOBAL",
        "evidence_urls": [
            "https://arxiv.org/abs/2604.20823",
            "https://en.wikipedia.org/wiki/Cats_and_the_Internet#Cat_distribution_system",
        ],
        "theme_summary": "The Cat Distribution System meme reframes cat adoption as serendipity. Make a rescue-note style pack about stray cats choosing people, avoiding generic cat mood memes already in the catalog.",
        "series_name": "Cat Distribution System Rescue Notes",
        "pack_archetype": "pet_adoption_meme_pack",
        "priority": "high",
        "palette": "cream paper, tuxedo black, ginger orange, soft gray, adoption teal, warm pink, mailbox blue",
        "style_anchor": "Warm cat adoption meme sticker sheet, scrapbook rescue notes, little street cats, doorsteps, cardboard boxes, maps, found-family feeling, clean cute vector-gouache hybrid, no brand logos, no famous meme likeness, no existing cat cafe or affirmation theme.",
        "preview_briefs": [
            {"preview_idx": 1, "theme": "assigned by the universe", "stickers": [
                "Assigned To You / tiny tabby sitting in a cardboard box with delivery label",
                "System Match / clipboard with pawprint check mark and cat tail curl",
                "Not A Choice / ginger cat walking through an open apartment door",
                "You Have Been Selected / official-looking teal badge with paw seal",
                "Front Porch Delivery / kitten in blanket beside flower pot and mail",
                "Random Cat Event / calendar square with paw confetti",
                "The Cat Chose Me / speech bubble over shy black cat",
                "Unexpected Roommate / tiny cat beside house key and rent note",
                "Cosmic Adoption / stars guiding a cat to a doorstep",
                "No Return Label / package box with cat ears and pink tape",
            ]},
            {"preview_idx": 2, "theme": "rescue checklist", "stickers": [
                "Food First / small bowl, water dish, and cautious kitten",
                "Vet Check Soon / reminder card with paw stethoscope icon",
                "Safe Room Setup / cozy bathroom corner with towel and toy",
                "Scan For Chip / scanner wand over friendly cat silhouette",
                "Found Cat Poster / simple notice with paw tabs, no real phone number",
                "Warm Blanket / folded fleece with sleeping kitten",
                "Slow Blink Treaty / two tiny eyes and heart-shaped blink marks",
                "Treat Negotiations / treat bag and cautious paw reach",
                "Name Pending / blank name tag with cat whiskers",
                "Welcome Home Maybe / open carrier with soft teal blanket",
            ]},
            {"preview_idx": 3, "theme": "street-to-sofa story", "stickers": [
                "Alley To Armchair / path line from trash can to soft chair",
                "First Nap Indoors / cat curled on cushion with sun patch",
                "Window Seat Claimed / cat on sill watching birds",
                "Old Collar New Life / simple collar with heart charm",
                "From Hiss To Purr / two-panel badge with tiny sound waves",
                "Tiny Survivor / small cat with bandage and brave stars",
                "Sofa Ownership Papers / document stamped with pawprint",
                "Trust Loading / progress bar under shy cat face",
                "Kitchen Inspector / cat peeking around cabinet",
                "Forever Foster Fail / heart-shaped adoption folder",
            ]},
            {"preview_idx": 4, "theme": "algorithm humor", "stickers": [
                "Pawgorithm Approved / laptop screen with pawprint code marks",
                "Matching In Progress / spinning yarn ball loading icon",
                "Nearest Human Found / map pin on apartment block",
                "High Compatibility / cat and human hand with spark meter",
                "System Update: Cat / notification card with whisker icon",
                "Random Encounter Rate / chart line ending in cat silhouette",
                "You Were Chosen / big stamp on cream paper",
                "Meow-Based Routing / dotted route with fish marker",
                "Adoption Patch Notes / paper sheet with tiny paw bullets",
                "Bug Or Feature / cat sitting on keyboard, no brand marks",
            ]},
            {"preview_idx": 5, "theme": "new cat parent kit", "stickers": [
                "Starter Litter Box / clean litter scoop and teal mat",
                "Emergency Squeeze Treat Fund / treat tube jar with coin label, no brand",
                "Toy Variety Pack / feather wand, ball, and crinkle mouse",
                "Cardboard Throne / box castle with cat peeking out",
                "Quiet Voice Zone / sign with moon and tiny paw",
                "Tiny ID Tag / blank heart tag and collar loop",
                "First Family Photo / instant photo frame with cat ears",
                "Adopted By A Cat / ribbon badge with paw and stars",
                "Home Trial Success / checklist with three teal checks",
                "The System Works / happy cat loaf on welcome mat",
            ]},
        ],
    },
    {
        "topic_name": "Pet-Friendly Weekend Travel Kit",
        "query": "2026 pet travel trend pet-friendly holidays dogs cats",
        "hot_score": 90,
        "region": "US/UK",
        "evidence_urls": [
            "https://www.thesun.co.uk/news/39314607/pet-owners-holiday-furry-friends/",
            "https://en.wikipedia.org/wiki/Pet_humanization",
        ],
        "theme_summary": "Pet owners increasingly plan trips around their animals. Make a pet travel kit sticker pack for weekend getaways, hotels, road snacks, and pet-friendly stops; distinct from existing generic road-trip/camping packs.",
        "series_name": "Pet-Friendly Weekend Travel Kit",
        "pack_archetype": "pet_travel_pack",
        "priority": "high",
        "palette": "sky blue, leash red, travel tan, grass green, luggage navy, cream white, sunny yellow",
        "style_anchor": "Pet-friendly travel sticker sheet, dogs and cats on weekend getaways, luggage tags, car seats, bowls, motel signs, trail maps, clean playful vector style, no airline logos, no destination trademarks, pet-specific not generic road trip.",
        "preview_briefs": [
            {"preview_idx": 1, "theme": "packing list", "stickers": [
                "Pet Packing List / clipboard with leash, bowl, toy, and check marks",
                "Favorite Blanket / rolled blanket tied with paw ribbon",
                "Travel Bowl / collapsible bowl with water splash",
                "Snack Pouch / treat pouch clipped to tiny backpack",
                "Poop Bag Hero / dispenser with cape and sparkle lines",
                "Medicine Reminder / small pill case with paw label",
                "Tiny Towel / towel roll with muddy pawprint",
                "Backup Collar / extra collar and tag on cream card",
                "Toy From Home / plush bone and catnip mouse duo",
                "Ready To Roll / suitcase with pawprint stickers",
            ]},
            {"preview_idx": 2, "theme": "car ride crew", "stickers": [
                "Backseat Navigator / dog in travel harness with map",
                "Window Sniff Stop / happy snout by car window",
                "Cat Carrier Calm / cat carrier with lavender blanket",
                "Rest Stop Stretch / leash loop beside roadside sign",
                "Water Break / bottle pouring into travel bowl",
                "No Front Seat / safety badge with pet car seat",
                "Playlist For Paws / generic music note and paw icons",
                "Are We There Yet / speech bubble beside sleepy pet",
                "Car Seat Captain / small dog booster seat badge",
                "Paw Prints On The Map / route line with paw pins",
            ]},
            {"preview_idx": 3, "theme": "pet-friendly stay", "stickers": [
                "Pet-Friendly Stay / motel key tag with paw symbol",
                "No Extra Fees Please / receipt with tiny paw and stars",
                "Lobby Manners / sitting dog beside suitcase",
                "Do Not Disturb Pet Napping / hotel door hanger",
                "Elevator Buddy / leash and elevator arrows badge",
                "Bed Permission Granted / pet on folded hotel blanket",
                "Quiet Hallway Paws / soft pawprints in corridor",
                "Welcome Treat / small biscuit on pillow card",
                "Room Inspection / cat peeking under hotel chair",
                "Checkout Snuggles / suitcase, blanket, and sleepy pet",
            ]},
            {"preview_idx": 4, "theme": "outdoor stops", "stickers": [
                "Trail Sniff Certified / trail sign with paw and leaf",
                "Park Bench Break / dog leash around sunny bench",
                "Shade First / umbrella over water bowl and pet",
                "Bug Check / comb, leaf, and tiny tick warning icon",
                "Paw Balm Stop / balm tin with mountain label",
                "Beach Towel Paws / pet towel with shell and pawprints",
                "Lake Lookout / dog and cat silhouettes watching water",
                "Picnic Guard / pet guarding snack basket politely",
                "Leash Lane / path sign with red leash",
                "Leave No Trace Paws / clean trail badge with bag icon",
            ]},
            {"preview_idx": 5, "theme": "travel memories", "stickers": [
                "My Pet Was Here / passport-style stamp with paw",
                "Vacation Mood / sunglasses on dog and cat duo",
                "Tiny Souvenir / bandana, postcard, and treat bag",
                "Photo Op Sit / camera frame with obedient pet pose",
                "Road Trip Nap / pet sleeping on travel pillow",
                "Best Co-Pilot / ribbon badge with paw wheel icon",
                "Weekend Explorer / backpack with leash and stars",
                "Home Safe / house icon, car, and tired pet",
                "Paws Set Go / generic travel agency sign, no brand",
                "Same Trip Next Week / calendar sticker with paw circle",
            ]},
        ],
    },
    {
        "topic_name": "Barkitecture Pet Room Makeover",
        "query": "barkitecture pet room design pet home decor trend 2026",
        "hot_score": 88,
        "region": "US",
        "evidence_urls": [
            "https://www.theguardian.com/wellness/2023/nov/15/pet-friendly-interior-home-design-barkitecture",
            "https://www.marketwatch.com/story/petco-is-leaning-on-services-fresh-food-and-pet-tarantulas-and-it-is-paying-off-3dd720f7",
        ],
        "theme_summary": "Barkitecture and pet humanization make pet rooms, feeding stations, crate nooks, and grooming corners highly sticker-friendly. Build a decor-forward pet room makeover pack.",
        "series_name": "Barkitecture Pet Room Makeover",
        "pack_archetype": "pet_home_decor_pack",
        "priority": "high",
        "palette": "sage green, warm beige, terracotta, matte black, oat cream, soft blush, wood brown",
        "style_anchor": "Stylish pet interior design sticker sheet, cozy dog and cat rooms, feeding stations, crate furniture, toy bins, grooming corners, calm modern home-decor palette, clean vector with soft shadows, no real furniture brands.",
        "preview_briefs": [
            {"preview_idx": 1, "theme": "pet room reveal", "stickers": [
                "Pet Room Reveal / arched doorway with paw doormat",
                "Tiny Suite / dog bed under gallery wall",
                "Cat Corner Upgrade / cat tree beside framed art",
                "Before And Pawfter / split badge with paint roller",
                "Designated Nap Zone / floor cushion and sleepy pet",
                "Custom Name Sign / blank wooden plaque with paw",
                "Mood Board Paws / swatches, leash, and tiny bed sketch",
                "Cozy Crate Nook / crate styled like side table",
                "Welcome To My Room / hanging sign with paw tassel",
                "Pet Parent Project / tape measure and pawprints",
            ]},
            {"preview_idx": 2, "theme": "feeding station", "stickers": [
                "Built-In Bowls / cabinet drawer with double bowls",
                "Snack Drawer / labeled treat drawer with bone handle",
                "Hydration Station / fountain bowl on sage mat",
                "No Crumbs Zone / placemat with terracotta border",
                "Dinner Bell / small bell with paw ribbon",
                "Kibble Canister / matte jar with scoop and tag",
                "Fresh Food Fridge / mini fridge icon with paw magnet",
                "Meal Prep Paws / containers with tiny labels",
                "Cat Cafe Shelf / raised cat bowl on wood stand",
                "Clean Bowl Club / sparkle badge with empty bowl",
            ]},
            {"preview_idx": 3, "theme": "toy and storage", "stickers": [
                "Toy Rotation / basket with weekly labels",
                "Leash Wall / hooks with collars and bandanas",
                "Ball Bin / round basket full of tennis balls",
                "Cat Toy Drawer / feather toys and crinkle mouse",
                "Puzzle Shelf / enrichment toys stacked neatly",
                "Tiny Laundry / basket of pet blankets",
                "Grooming Caddy / brush, comb, and nail file",
                "Treat Jar Row / three jars with paw labels",
                "Lost Sock Archive / dog bed with single sock",
                "Storage But Cute / lidded bin with paw decal",
            ]},
            {"preview_idx": 4, "theme": "wash and grooming", "stickers": [
                "Mudroom Rinse / little dog shower with tiled wall",
                "Paw Wash Station / faucet, towel, and paw mat",
                "Brush Day / slicker brush with fur cloud",
                "Bath Token / rubber duck and shampoo bottle, no brand",
                "Towel Burrito / wrapped sleepy pet",
                "Drying Zone / fan, towel hook, and wet pawprints",
                "Spa Appointment / calendar card with paw circle",
                "Clean Ears Club / gentle ear wipe icon",
                "Nail Trim Courage / clipper with tiny star medal",
                "Fresh Bandana / folded bandana on wood stool",
            ]},
            {"preview_idx": 5, "theme": "renter-friendly hacks", "stickers": [
                "Peel And Paw / removable wallpaper roll with paw pattern",
                "No-Drill Cat Shelf / shelf with sticky mount symbol",
                "Tiny Apartment Big Pet / floorplan with paw path",
                "Foldaway Gate / collapsible pet gate badge",
                "Window Perch Hack / suction perch and sun patch",
                "Hidden Litter Nook / cabinet door with cat cutout",
                "Rental Deposit Please / key tag with cautious paw",
                "Washable Rug / rug corner with clean check mark",
                "Removable Hook Leashes / hooks with leash loops, no brand",
                "Cozy Without Renovation / cushion stack and plant",
            ]},
        ],
    },
    {
        "topic_name": "Pup Cup Bakery Birthday Party",
        "query": "dog bakery pup cup pet birthday party trend 2026 pet humanization",
        "hot_score": 87,
        "region": "US",
        "evidence_urls": [
            "https://www.marketwatch.com/story/petco-is-leaning-on-services-fresh-food-and-pet-tarantulas-and-it-is-paying-off-3dd720f7",
            "https://en.wikipedia.org/wiki/Dog_bakery",
        ],
        "theme_summary": "Fresh pet food, dog bakeries, pup cups, and pet birthdays fit the pet-humanization market. Make a cute bakery-party sticker pack; avoid using Starbucks or other brand references.",
        "series_name": "Pup Cup Bakery Birthday Party",
        "pack_archetype": "pet_party_food_pack",
        "priority": "high",
        "palette": "bakery pink, butter yellow, chocolate brown, mint green, cream frosting, party blue, cherry red",
        "style_anchor": "Cute dog bakery and pet birthday sticker sheet, pup cups, dog-safe cakes, biscuit trays, party hats, bakery counter, joyful but non-branded, clean kawaii vector-gouache style, no real cafe logos, no unsafe food emphasis.",
        "preview_briefs": [
            {"preview_idx": 1, "theme": "bakery counter", "stickers": [
                "Pup Cup Please / whipped cream cup with paw sprinkle, no brand",
                "Dog Bakery Box / pink pastry box with bone window",
                "Fresh Biscuits / tray of bone-shaped biscuits",
                "Treat Counter / tiny bakery case with pet-safe labels",
                "Peanut Butter Smile / jar and biscuit spoon, no brand",
                "Frosting Nose / dog with frosting dot and party sparkle",
                "Biscuit Menu / chalkboard with paw prices, no real currency",
                "Takeout Treats / paper bag with paw stamp",
                "Mini Muffin For Dogs / safe-looking pupcake with flag",
                "Bakery Bandana / dog bandana with cupcake print",
            ]},
            {"preview_idx": 2, "theme": "birthday setup", "stickers": [
                "Birthday Barkday / cake with bone candle",
                "Gotcha Day Party / adoption anniversary banner",
                "Party Hat Pup / dog in tiny cone hat",
                "One More Treat / speech bubble beside cake slice",
                "Guest Of Honor / ribbon badge with paw and candle",
                "Confetti Collar / collar with streamers and bell",
                "Photo Booth Sit / frame with paw props",
                "Birthday Bandana / folded bandana with stars",
                "Treat Tower / stacked dog-safe cookies",
                "Make A Wish / candle flame shaped like paw",
            ]},
            {"preview_idx": 3, "theme": "cat treat cafe", "stickers": [
                "Catnip Cookie / fish-shaped cookie with mint leaf",
                "Tiny Cream Saucer / saucer with paw foam art",
                "Meow Muffin / small cat-safe muffin with flag",
                "Purrfect Plate / plate with tiny treats",
                "Cafe Window Cat / cat at bakery window",
                "Fish Biscuit Box / blue box with fish cutout",
                "Treat Tasting / cat sniffing three mini plates",
                "Nap After Snacks / cat curled beside crumbs",
                "Cat Party Hat / tiny hat beside skeptical cat",
                "Bakery Loaf / cat loaf on gingham cloth",
            ]},
            {"preview_idx": 4, "theme": "party guests", "stickers": [
                "RSVPaw / invitation card with paw seal",
                "Good Sit Guest / polite dog sitting by treat table",
                "Snack Table Security / pet guarding cupcake stand",
                "Party Pack Walk-In / three pets with balloons",
                "No Human Cake / crossed-out chocolate cake icon",
                "Safe Treats Only / shield badge with biscuit",
                "Birthday Nap Break / pet sleeping under bunting",
                "Gift Bag Sniff / party favor bag with pet nose",
                "Cake Crumb Detective / magnifier over crumbs",
                "Thank You Treats / favor tag with pawprint",
            ]},
            {"preview_idx": 5, "theme": "bakery merch", "stickers": [
                "Barkery Club / round membership badge",
                "Fresh From The Oven / oven mitt with paw",
                "Pupcake Patrol / cupcake and tiny badge",
                "Treat Tester / clipboard with biscuit ratings",
                "Birthday Subscription / box with monthly paw label",
                "Chef Hat Pup / dog chef hat with whisk",
                "Tiny Rolling Pin / rolling pin with paw dough",
                "Sprinkle Safe / jar of colorful safe-looking sprinkles",
                "Bakery Tote / tote bag with bone print",
                "Sugar-Free Sweetheart / heart cookie with check mark",
            ]},
        ],
    },
    {
        "topic_name": "Pet Wellness Tracker Check-In",
        "query": "2026 pet wellness behavior changes health anxiety nutrition pet parents",
        "hot_score": 89,
        "region": "US",
        "evidence_urls": [
            "https://nypost.com/2026/01/13/lifestyle/the-top-behavior-changes-that-worry-pet-owners-the-most-survey/",
            "https://en.wikipedia.org/wiki/Pet_humanization#Pet_healthcare",
        ],
        "theme_summary": "Pet parents are tracking happiness, health, diet, anxiety, and vet guidance. Make a wellness tracker sticker pack with logs, reminders, smart collars, nutrition notes, and calm check-ins.",
        "series_name": "Pet Wellness Tracker Check-In",
        "pack_archetype": "pet_wellness_pack",
        "priority": "high",
        "palette": "clinic teal, calming lavender, soft yellow, white, slate gray, mint green, coral accent",
        "style_anchor": "Modern pet wellness tracker sticker sheet, vet notes, health logs, mood check-ins, nutrition reminders, calm anxiety support, smart collar icons, friendly medical-adjacent vector style, no real app logos, no medical claims.",
        "preview_briefs": [
            {"preview_idx": 1, "theme": "daily check-in", "stickers": [
                "Mood Check / pet face meter with calm lavender marks",
                "Water Goal / bowl with hydration progress ring",
                "Meal Logged / food bowl and checklist card",
                "Walk Complete / leash route with green check",
                "Play Minutes / ball and timer badge",
                "Nap Quality / moon over pet bed",
                "Poop Report / discreet bag icon with clipboard",
                "Weight Note / scale with pawprint and pencil",
                "Energy Level / battery icon with wagging tail",
                "All Good Today / teal shield with paw heart",
            ]},
            {"preview_idx": 2, "theme": "vet visit notes", "stickers": [
                "Vet Day / carrier, leash, and calendar circle",
                "Questions For Vet / notepad with paw bullets",
                "Nutrition Talk / food scoop and clinic chart",
                "Vaccine Reminder / calendar card with gentle syringe icon",
                "Dental Check / toothbrush and smiling pet tooth",
                "Ear Check / ear icon with tiny magnifier",
                "Allergy Watch / flower, paw, and alert dot",
                "Follow-Up Card / appointment card with teal check",
                "Brave Patient / medal with paw and star",
                "Treat After Visit / biscuit reward badge",
            ]},
            {"preview_idx": 3, "theme": "anxiety support", "stickers": [
                "Calm Corner / pet bed with lavender blanket",
                "Thunder Plan / cloud, blanket, and safe room sign",
                "Separation Routine / door, clock, and chew toy",
                "Slow Breaths Human / reminder card with paw heart",
                "Enrichment Time / puzzle feeder and sparkle",
                "Snuffle Mat / mat with hidden treat dots",
                "Lick Mat Chill / textured mat with calming swirls",
                "Quiet Hours / moon sign with sleeping pet",
                "Safe Space / crate nook with open door",
                "Tiny Wins / star chart for brave moments",
            ]},
            {"preview_idx": 4, "theme": "smart care tools", "stickers": [
                "Smart Collar / generic collar with pulse dot",
                "GPS Check / map pin with pawprint, no brand",
                "Activity Ring / three colorful rings around paw",
                "Feeder Schedule / automatic feeder with timer",
                "Water Fountain Clean / fountain and sparkle badge",
                "Camera Check-In / generic home camera with paw icon",
                "Reminder Ping / phone notification with paw, no app logo",
                "Medication Timer / pill case and alarm clock",
                "Brush Streak / grooming comb with calendar stars",
                "Data But Cute / chart card with wag line",
            ]},
            {"preview_idx": 5, "theme": "nutrition and routine", "stickers": [
                "New Food Slowly / seven-day bowl transition chart",
                "Ingredient Notes / label card with fish and leaf icons",
                "Portion Scoop / scoop with measuring line",
                "Treat Budget / jar with daily treat tokens",
                "Sensitive Tummy / gentle stomach icon with paw",
                "Fresh Water First / blue bottle and bowl",
                "Routine Wins / morning and evening checklist",
                "Healthy Coat / brush and shiny fur sparkle",
                "Joint Care Reminder / stairs, ramp, and paw",
                "Ask The Vet / speech bubble with clinic teal cross and paw",
            ]},
        ],
    },
    {
        "topic_name": "Pet Parent Budget Receipts",
        "query": "2026 pet parenting cost pet spending vet bills treats budget",
        "hot_score": 91,
        "region": "US",
        "evidence_urls": [
            "https://www.axios.com/local/denver/2026/06/09/cost-of-pet-parenting-soaring-bank-of-america",
            "https://nypost.com/2026/02/23/lifestyle/3-in-10-pet-owners-spend-more-on-pet-than-their-own-health-report/",
        ],
        "theme_summary": "Rising pet costs and pet-parent spending are timely. Make a funny receipt/budget sticker pack about vet bills, treat funds, insurance, grooming, and 'my pet has a better life than me'.",
        "series_name": "Pet Parent Budget Receipts",
        "pack_archetype": "pet_parent_money_meme_pack",
        "priority": "high",
        "palette": "receipt white, money green, coral red, ink black, coupon yellow, soft blue, coin gold",
        "style_anchor": "Funny pet parent budget sticker sheet, receipts, coupons, vet bills, treat funds, grooming invoices, spoiled pet lifestyle, bold clean vector with paper textures, no real bank or store logos, no medical claims.",
        "preview_briefs": [
            {"preview_idx": 1, "theme": "receipt jokes", "stickers": [
                "Pet Receipt Longer Than Mine / curling receipt with paw total",
                "Treats Again / checkout slip with biscuit line items",
                "Worth Every Penny / coin stack and happy pet face",
                "Budget? Never Met Her / wallet with pawprint bite mark",
                "My Pet Has A Better Life / luxury bed on receipt paper",
                "Tiny Tax Deduction Please / calculator with paw buttons",
                "Emergency Snack Fund / jar of coins and biscuits",
                "Subscription Box Day / parcel with money-green tape",
                "Checkout Pawprint / receipt stamped with paw",
                "No Regrets Total / grand total with heart icon",
            ]},
            {"preview_idx": 2, "theme": "vet bill humor", "stickers": [
                "Vet Bill Survivor / ribbon badge with clipboard",
                "Mystery Limp Fund / coin jar with question mark paw",
                "Insurance Maybe / umbrella over pet and receipt",
                "Nail Trim Invoice / tiny paw and price tag",
                "Annual Checkup Day / calendar and stethoscope paw",
                "Why Are You Expensive / speech bubble to innocent pet",
                "Credit Card Courage / generic card with paw chip",
                "Paid In Treats / receipt with biscuit payment",
                "Health Comes First / heart shield and invoice",
                "Budget Recovery Nap / human wallet under sleeping pet",
            ]},
            {"preview_idx": 3, "theme": "grooming spend", "stickers": [
                "Spa Day Again / grooming table and sparkle brush",
                "Fluffy Upgrade / pet with fresh bandana",
                "Deshed Deluxe / fur cloud and comb",
                "Bath Tip Jar / jar with bubbles and coins",
                "Fresh Trim Who Dis / pet silhouette with scissors icon",
                "Clean Paws Fee / paw wash receipt",
                "Bandana Add-On / folded bandana and price tag",
                "Salon Selfie / mirror frame with pet ears",
                "Fur Everywhere Budget / lint roller and money",
                "Worth The Fluff / fluffy pet on coupon label",
            ]},
            {"preview_idx": 4, "theme": "treat economy", "stickers": [
                "Treat Inflation / biscuit price chart trending up",
                "One More Bag / shopping bag full of snacks",
                "Coupon Clipper Pet Parent / scissors and treat coupon",
                "Bulk Biscuit Math / calculator with biscuit keys",
                "Snack Treasury / safe box full of treats",
                "Premium Kibble Club / bag with gold paw seal, no brand",
                "Taste Test Budget / three bowls and coin stack",
                "Pantry Audit / shelf of cans and check marks",
                "Human Groceries Later / pet food first grocery list",
                "Treat Allowance / weekly envelope with paw stamp",
            ]},
            {"preview_idx": 5, "theme": "spoiled but loved", "stickers": [
                "CEO Of My Paycheck / pet on office chair with invoice",
                "Spoiled Department / badge with crown and paw",
                "Pet Parent Math / one pet plus many receipts",
                "They Deserve It / heart around shopping cart",
                "Rent Free Roommate / pet bed beside house key",
                "My Wallet Says Meow / wallet with cat ears",
                "My Wallet Says Woof / wallet with dog nose",
                "Budget Meeting / pet sitting on calculator",
                "Luxury Nap ROI / pet sleeping on fancy cushion",
                "Love Is The Line Item / receipt ending with heart total",
            ]},
        ],
    },
]


if __name__ == "__main__":
    raise SystemExit(base.main())
